site_name: YUNA KnowledgeBase
repo_url: https://github.com/yuna2017/knowledgeBase
copyright: YUNA devBranch
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - 简介:
    - Getting Started: index.md
    - 如何参与: intro/htc.md
    - F.A.Q.: intro/faq.md
    - 关于本项目: intro/about.md
  - 校园网:
    - 校园网是什么: campusNet/intro.md
    - 连接与认证方式: campusNet/connect.md
    - 路由器配置:
      - TP-LINK: campusNet/router/tplink.md
    - 进阶用法: campusNet/advanced.md
    - 速度慢？与常见问题: campusNet/faq.md
  - 线上服务:
    - 统一身份认证: service/auth.md
    - 教务系统: service/jwc.md
    - 一网通办:
      - 简介: service/ehall/intro.md
      - 成绩查询: service/ehall/grade.md
      - 综合测评: service/ehall/zongce.md
  - 正版化:
    - 为什么要使用正版: ms/intro.md
    - Windows 激活: ms/windows.md
    - Office 激活: ms/office.md
    - 福昕 PDF 编辑器: ms/foxin.md
  - 校园邮箱:
    - 什么是校园邮箱: mail/intro.md
    - 申领与设置: mail/signup.md
    - 可供白嫖的资源: mail/res.md
